version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin 010426082127.dkr.ecr.us-west-2.amazonaws.com
  build:
    commands:
      - echo Build started
      - docker build -t myapp .
      - docker tag myapp:latest 010426082127.dkr.ecr.us-west-2.amazonaws.com/myapp:latest
  post_build:
    commands:
      - echo Pushing to ECR...
      - docker push 010426082127.dkr.ecr.us-west-2.amazonaws.com/myapp:latest
artifacts:
  files:
    - appspec.yml
    - scripts/run_docker.sh
